### ISSUE TITLE
DataAnalysisPlugin: TODO

### ISSUE THREAD

**Issue by yiyungent** [yiyungent/KnifeHub#28]
DataAnalysisPlugin

- [ ] BaseEntity.TenantId 
   - 用户用租户实现, 更简单, 针对此种更多隔离情况, 更易用
- [ ] UserEntity: BaseEntity
   - UserName, Password, Token, GitHubEntity
- [ ] 通过 GitHub 注册并登录
- [ ] `/plugins/DataAnalysisPlugin` 全移除 `PluginCore.Admin` 权限, 此为前台, 由登录用户具体授权
- [ ] 后台管理独立页面 (`/plugins/DataAnalysisPlugin/admin`): `PluginCore.Admin` 权限
